
server:
  port: 8080
spring:
  application:
    name: identify
  datasource:
    url: jdbc:mysql://localhost:3306/identifyDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
jwt:
  refresh-token-key: "7RNUqJlIkY3IuGxPKbC7GoGDW40BdtEviJxdjqXSCqrptnnqC98+hyRUB87BxzQG"
  access-token-key: "ZeroJdXEgYS9h2Qt2WuiMmNUquk5X1w++iX+4SCI2ZmTHK9Htuz6OmsDDkq1huB8"
  access-valid-duration: 5000 #in milliseconds, 1000 milliseconds = 1 second, 1h
  refresh-valid-duration: 1209600000 #in milliseconds, 14 days
