#profile prod
server:
  port: 8085
spring:
  application:
    name: identify
  datasource:
    url: jdbc:mysql://localhost:3306/identifyDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

application:
  security:
    jwt:
      secret-key: "c60GncVRxS9g4yssGdaO3KyUYWSC7hTGq5lZqNYwUpsCsNaMLV2fR5W0h95U1y3M"
      expiration: 60000 # 60 seconds
      refresh-token:
        expiration: 604800000  # 7 days
    cookie:
      secure: true
      same-site: Lax