services:
  # 1️⃣ Database Service (MySQL)
  mysql:
    image: mysql:8.0.43-debian               # Dùng image chính thức của MySQL
    container_name: mysql                    # Tên container (tùy chọn)
    restart: always                          # Tự khởi động lại nếu bị tắt
    environment:                             # Các biến môi trường của MySQL
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identifyDB
    ports:
      - "3306:3306"                          # public port → host:container
    volumes:
      - dbdata:/var/lib/mysql                # volume để giữ dữ liệu khi restart
    networks:
      - dev001-network                     # mạng nội bộ riêng cho project
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
  # 2️⃣ Backend Service (Spring Boot)
  identify-service:
    image: dev00001/identify-service:0.0.2
    container_name: identify-service
    restart: always
    env_file:                                # nạp biến môi trường từ file .env
      - ../BACKEND/.env
    ports:
      - "8080:8080"                          # public port của backend
    depends_on:
      mysql: # đảm bảo mysql chạy trước backend
        condition: service_healthy # ✅ chờ MySQL healthy
    networks:
      - dev001-network                     # cùng network → kết nối được MySQL
volumes:
  dbdata:                                    # volume giữ data MySQL (tránh mất data)
networks:
  dev001-network:                          # mạng riêng, tự tạo
    driver: bridge