
server:
  port: 8080
spring:
  application:
    name: identify
  datasource:
    url: jdbc:mysql://localhost:3306/identifyDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
jwt:
  signerKey: "7RNUqJlIkY3IuGxPKbC7GoGDW40BdtEviJxdjqXSCqrptnnqC98+hyRUB87BxzQG"
  valid-duration: 3600000 #in milliseconds, 1000 milliseconds = 1 second
  refresh-valid-duration: 86400000 #in milliseconds
